### PR TITLE
Add Postgres metadata

### PR DESCRIPTION
**Pull request by rocel**
Hello,

as promised this is the implementation to support Postgres as metadata store raised in https://github.com/rovio/rovio-ingest/issues/15.

I could **not** yet **fully** try it on our platform.

Cheers

### CODE REVIEW

**Comment by vivek-balakrishnan-rovio** [comment]
Hi @rocel ,
Thanks for contribution. 

I quickly took a look at the PR and the changes seem mostly fine.
I will take a detailed look later today and update if any changes are required :)

However, before we merge this can we do the following:
1. Can you add a test for PostgresSQL using [Testcontainers](https://www.testcontainers.org/modules/databases/postgres/) module.  I am thinking we can write a test for [MetadataUpdater.java](https://github.com/rovio/rovio-ingest/blob/main/src/main/java/com/rovio/ingest/util/MetadataUpdater.java)  (to test both Mysql and PostgresSQL) instead updating the integration tests. 

2. Can you please sign then [Contributor License Aggrement](https://github.com/rovio/rovio-ingest/blob/main/CONTRIBUTING.md) https://github.com/rovio/rovio-ingest/blob/main/CONTRIBUTING.md

Once again thanks for the contribution.

**Comment by vivek-balakrishnan-rovio** [comment]
Hi @rocel ,

Can you please let me know when you have sent the email to sign the CLA, so that I can make sure that it is attended to promptly.

Thanks,
Vivek

**Comment by rocel** [comment]
Hi @vivek-balakrishnan-rovio ,
As written in the [documentaiton](https://github.com/rovio/rovio-ingest/blob/main/CONTRIBUTING.md#contributor-license-agreement), I wrote an email to opensource@rovio.com few days ago and I'm waiting for a response before going further with the PR.

Cheers,

**Comment by vivek-balakrishnan-rovio** [comment]
@rocel Sorry for the delay. I will check about the status of your CLA agreement and come back to you
Thanks,
Vivek

**Comment by vivek-balakrishnan-rovio** [comment]
Hi @rocel,
Sorry for the delay. Unfortunately it is summer vacation time here at Finland.
However, we will soon reply back to your CLA email.
 
 Thanks & Regards,
Vivek

**Comment by rocel** [comment]
thanks!

**Comment by rocel** [comment]
@vivek-balakrishnan-rovio Hi! I signed the CLA, I will now carry on on this PR.

Any recommendation on how to architecture the tests that are already specialized with MySQL (it uses a mysql testcontainer)

**Comment by juhoautio-rovio** [comment]
For the testing, could you try adding `org.testcontainers:postgresql` as a dependency in pom.xml in the same way that we have the mysql test container there? With this you could at least try initially that everything works as expected.

For the "architecture", could you consider organizing the tests something like this: https://dzone.com/articles/integration-test-with-multiple-databases-1? To run all tests (that use a DB) against both DB types.

That would probably mean that test duration is almost 2x longer than before. We can consider having a standard way to run the tests only for one DB type, so that one can validate changes faster locally. Github actions would always run the full integration suite though. But optimizations like this can be left as a future improvement IMO.

**Comment by vivek-balakrishnan-rovio** [comment]
@rocel As for suggested by Juho, we need to add `org.testcontainers:postgresql` dependency in pom file. Also, can you please try if everything works as intended with postgres.

 As far as refactoring the test, I think we can do it in step. As suggested earlier, lets add a unit test for [MetadataUpdater.java](https://github.com/rovio/rovio-ingest/blob/main/src/main/java/com/rovio/ingest/util/MetadataUpdater.java) that runs against both Mysql and PostgresSQL.
 
we can later refactor other tests in a separate PR to run against both DBs.

**Comment by juhoautio-rovio** [comment]
Including this change in https://github.com/rovio/rovio-ingest/pull/31. I have there added the unit test coverage as well. Thanks!

**Pull request closed without merging**
